# Generated by Django 5.1.5 on 2025-03-02 14:16

import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='products/', validators=[store.models.max_upload_with_ext]),
        ),
    ]
