# Generated by Django 5.1.5 on 2025-02-21 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('mobile', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('sex', models.BooleanField(blank=True, null=True)),
                ('password', models.CharField(blank=True, max_length=250, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('birthday', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'person',
                'verbose_name_plural': 'personha',
                'db_table': 'human',
                'ordering': ['create_at'],
            },
        ),
    ]
