# Generated by Django 5.1.5 on 2025-02-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modellearn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='mobile',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
    ]
