# Generated by Django 5.1.5 on 2025-02-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modellearn', '0003_alter_person_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='mobile',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
    ]
