# Generated by Django 5.1.5 on 2025-02-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modellearn', '0004_alter_person_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='sex',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
