# Generated by Django 5.1.5 on 2025-02-22 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modellearn', '0005_personaddress'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='personaddress',
            table='person_address',
        ),
    ]
