# Generated by Django 5.1.5 on 2025-02-20 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modellearn', '0005_alter_person_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='sex',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
