# Generated by Django 5.1.5 on 2025-02-21 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modellearn', '0006_alter_person_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='birthday',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
