# Generated by Django 5.1.5 on 2025-02-25 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modellearn', '0006_alter_personaddress_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['create_at'], 'verbose_name': 'person', 'verbose_name_plural': 'persons'},
        ),
    ]
