# Generated by Django 5.1.5 on 2025-02-21 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modellearn', '0008_remove_person_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='password',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
