# Generated by Django 5.1.5 on 2025-03-09 14:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_alter_bookapi_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='productapi',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 9, 14, 42, 0, 438819, tzinfo=datetime.timezone.utc)),
        ),
    ]
