# Generated by Django 5.1.5 on 2025-03-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_productapi_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productapi',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
