# Generated by Django 5.1.5 on 2025-03-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0006_alter_productapi_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productapi',
            name='create_at',
            field=models.DateField(),
        ),
    ]
