# Generated by Django 5.1.5 on 2025-02-25 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user_custom',
        ),
    ]
